version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      # compat is not a codeclimeate supported eslint plugin
      compat/compat:
        enabled: false
      # indent rules on codeclimate seem to be different from
      # the local ones - probably because cc uses an older version
      # of eslint
      indent:
        enabled: false
exclude_patterns:
  - ".github/"
  - "test/"
  - "types/"
  - "**/node_modules/"