sudo: required

language: node_js

node_js:
  - "10"
  - "12"
  - "13"
  - "14"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "if test `node --version | cut -c 2,3` = 14; then npm run check; else npm test; fi"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules
