sudo: false

language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

install:
  - npm install

script:
  - 'if test `node --version | cut -c 2` != 4; then npm run check; else npm test; fi'

cache:
  directories:
    - node_modules
