name: install, lint and test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
          - 19.x
        platform:
          - ubuntu-latest
          - windows-latest
        exclude:
          - node-version: 16.x
            platform: windows-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm test
