name: Install, lint and test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - ^8.12
          - 10.x
          - 12.x
          - 13.x
        platform:
          - ubuntu-latest
          - windows-latest
        exclude:
          - node-version: ^8.12
            platform: windows-latest
          - node-version: 10.x
            platform: windows-latest
          - node-version: 13.x
            platform: windows-latest

    runs-on: ${{matrix.platform}}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install
        run: |
          # echo cache-hit ${{cache-hit}}
          echo env-cache-hit ${{env.cache-hit}}
          echo env ${{env}}
          node --version
          npm install
      - name: lint and test
        run: |
          node --version
          npm run check
        env:
          CI: true
